"""add OLAP indexes and summary table

Revision ID: 9bad212b1b92
Revises: e46ef46d0daf
Create Date: 2026-04-04 23:47:57.193724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bad212b1b92'
down_revision: Union[str, None] = 'e46ef46d0daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_timeline_summary',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('granularity', sa.String(), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('type_counts', sa.Text(), nullable=True),
    sa.Column('indicator_sample', sa.Text(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('total_indicators', sa.Integer(), nullable=True),
    sa.Column('unique_ips', sa.Integer(), nullable=True),
    sa.Column('unique_domains', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("granularity IN ('day', 'week')", name='ck_cts_granularity'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'granularity', 'period')
    )
    op.create_index('idx_campaign_indicators_campaign_observed', 'campaign_indicators', ['campaign_id', 'observed_at'], unique=False)
    op.create_index('idx_campaign_indicators_observed', 'campaign_indicators', ['observed_at'], unique=False)
    op.add_column('campaigns', sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_index('idx_indicators_first_seen_type', 'indicators', ['first_seen', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_indicators_first_seen_type', table_name='indicators')
    op.drop_index('idx_campaigns_status', table_name='campaigns')
    op.drop_column('campaigns', 'last_modified')
    op.drop_index('idx_campaign_indicators_observed', table_name='campaign_indicators')
    op.drop_index('idx_campaign_indicators_campaign_observed', table_name='campaign_indicators')
    op.drop_table('campaign_timeline_summary')
    # ### end Alembic commands ###
