"""initial schema

Revision ID: e46ef46d0daf
Revises: 
Create Date: 2026-04-04 02:21:01.021529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46ef46d0daf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target_sectors', sa.String(), nullable=True),
    sa.Column('target_regions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active', 'dormant', 'completed')", name='ck_campaigns_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("type IN ('ip', 'domain', 'url', 'hash')", name='ck_indicators_type'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_indicators_confidence'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value')
    )
    op.create_index(op.f('ix_indicators_first_seen'), 'indicators', ['first_seen'], unique=False)
    op.create_index(op.f('ix_indicators_last_seen'), 'indicators', ['last_seen'], unique=False)
    op.create_index(op.f('ix_indicators_type'), 'indicators', ['type'], unique=False)
    op.create_index(op.f('ix_indicators_value'), 'indicators', ['value'], unique=False)
    op.create_table('threat_actors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_origin', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('sophistication_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("sophistication_level IN ('low', 'medium', 'high', 'advanced')", name='ck_threat_actors_sophistication'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actor_campaigns',
    sa.Column('threat_actor_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_actor_campaigns_confidence'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ),
    sa.PrimaryKeyConstraint('threat_actor_id', 'campaign_id')
    )
    op.create_index('idx_actor_campaigns_actor', 'actor_campaigns', ['threat_actor_id'], unique=False)
    op.create_index('idx_actor_campaigns_campaign', 'actor_campaigns', ['campaign_id'], unique=False)
    op.create_table('campaign_indicators',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('indicator_id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'indicator_id')
    )
    op.create_index('idx_campaign_indicators_campaign', 'campaign_indicators', ['campaign_id'], unique=False)
    op.create_index('idx_campaign_indicators_indicator', 'campaign_indicators', ['indicator_id'], unique=False)
    op.create_table('indicator_relationships',
    sa.Column('source_indicator_id', sa.String(), nullable=False),
    sa.Column('target_indicator_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('first_observed', sa.DateTime(), nullable=True),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_indicator_relationships_confidence'),
    sa.ForeignKeyConstraint(['source_indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['target_indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('source_indicator_id', 'target_indicator_id', 'relationship_type')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('indicator_id', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_observations_indicator', 'observations', ['indicator_id'], unique=False)
    op.create_index('idx_observations_timestamp', 'observations', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_observations_timestamp', table_name='observations')
    op.drop_index('idx_observations_indicator', table_name='observations')
    op.drop_table('observations')
    op.drop_table('indicator_relationships')
    op.drop_index('idx_campaign_indicators_indicator', table_name='campaign_indicators')
    op.drop_index('idx_campaign_indicators_campaign', table_name='campaign_indicators')
    op.drop_table('campaign_indicators')
    op.drop_index('idx_actor_campaigns_campaign', table_name='actor_campaigns')
    op.drop_index('idx_actor_campaigns_actor', table_name='actor_campaigns')
    op.drop_table('actor_campaigns')
    op.drop_table('threat_actors')
    op.drop_index(op.f('ix_indicators_value'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_type'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_last_seen'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_first_seen'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
